version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create venv
            mkdir -p $HOME/.envs    
            python -m venv $HOME/.envs/testenv
            source $HOME/.envs/testenv/bin/activate
      - run:
          command: | # install deps and run tests
            pip install -e .[test]
            pytest --fulltrace
  test_pypi_publish:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create venv
            mkdir -p $HOME/.envs    
            python -m venv $HOME/.envs/testenv
            source $HOME/.envs/testenv/bin/activate
      - run:
          command: | # create whl, install twine and publish to Test PyPI
            pip install setuptools build twine
            python -m build
            twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create venv
            mkdir -p $HOME/.envs    
            python -m venv $HOME/.envs/testenv
            source $HOME/.envs/testenv/bin/activate
      - run:
          command: | # create whl, install twine and publish to Test PyPI
            cd pandas_predicates
            pip install setuptools build twine
            python -m build
            twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
